version: '3.8'

services:

  database:
    build: ./requirements/mariadb
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: frontend
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - WP_DEBUG
    restart: unless-stopped
    depends_on: 
      - database
    volumes:
      - webserv:/var/www/html
    networks:
      - inception
  
  webserver:
    build: ./requirements/nginx
    container_name: webserver
    restart: unless-stopped
    depends_on: 
      - wordpress
    ports:
      - 443:443
    volumes:
      - webserv:/var/www/html
    networks:
      - inception

networks:
  inception:
    name: inception
  
volumes:
  data:
    driver_opts:
      o: bind
      type: none
      device: /home/gundul/data/database
  webserv:
    driver_opts:
      o: bind
      type: none
      device: /home/gundul/data/webserver
