version: '3.8'

services:

  database:
    build: ./requirements/mariadb
    image:  mariadb:graja
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:graja
    container_name: frontend
    restart: unless-stopped
    depends_on: 
      - database
    volumes:
      - webserv:/var/www/html
    networks:
      - inception
  
  webserver:
    build: ./requirements/nginx
    image: nginx:graja
    container_name: webserver
    restart: unless-stopped
    depends_on: 
      - wordpress
    ports:
      - 443:443
    volumes:
      - webserv:/var/www/html
    networks:
      - inception

################
## Bonus part ##
################

  ftp:
    build: ./bonus/ftp
    image: ftp:graja
    container_name: ftp
    restart: unless-stopped
    depends_on: 
      - webserver
    ports:
      - 0.0.0.0:21:21
    volumes:
      - webserv:/var/run/vsftpd
    networks:
      - inception

  redis:
    build: ./bonus/redis
    image: redis:graja
    container_name: redis
    restart: unless-stopped
    depends_on: 
      - wordpress
    volumes:
      - webserv:/var/run/vsftpd
    networks:
      - inception

  adminer:
    build: ./bonus/adminer
    image: adminer:graja
    container_name: adminer
    depends_on: 
      - database
      - webserver
      - wordpress
    volumes:
      - webserv:/var/www/html
    networks:
      - inception

  minetest:
    build: ./bonus/minetest
    image: minetest:graja
    restart: unless-stopped
    container_name: minetest
    ports:
      - 30000:30000/udp
    networks:
      - inception

################
##  end Bonus ##
################

networks:
  inception:
    name: inception
  
volumes:
  data:
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_VOLUME_DATA}
  webserv:
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_VOLUME_WEBSERVER}
