version: '3.8'

services:

  database:
    build: ./requirements/mariadb
    volumes:
      - data:/val/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    depends_on: 
      - database
    volumes:
      - webserv:/usr/share/nginx/html
        #volumes_from:
        #- webserver:rw
    networks:
      - inception
  
  webserver:
    build: ./requirements/nginx
    depends_on: 
      - wordpress
    ports:
      - 443:443
    volumes:
      - webserv:/usr/share/nginx/html
    networks:
      - inception

networks:
  inception:
  
volumes:
  data:
    driver_opts:
      o: bind
      type: none
      device: /home/gundul/data/database
  webserv:
    driver_opts:
      o: bind
      type: none
      device: /home/gundul/data/webserver
